<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_StudentName</name>
   <tag></tag>
   <elementGuidId>befc179e-600b-4931-b7a0-d1881b83b9d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>html/body/div[1]/div[2]/table/tbody/tr/td/div[2]/table/tbody/tr/td[2]/div[2]/div[2]/div[2]/div/div[2]/div/div[2]/table/tbody/tr[2]/th/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/00Q3C000001ikiL?srPos=0&amp;srKp=00Q</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-seclke</name>
      <type>Main</type>
      <value>Lead</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-seclkh</name>
      <type>Main</type>
      <value>060b241e6b1208a51fab8f1941bfd799</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-seclki</name>
      <type>Main</type>
      <value>00Q3C000001ikiL</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-seclkp</name>
      <type>Main</type>
      <value>/00Q3C000001ikiL</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-seclkr</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousedown</name>
      <type>Main</type>
      <value>searchResultClick.mousedown(this, event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daniel Autoeleven</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Lead_body&quot;)/table[@class=&quot;list&quot;]/tbody[1]/tr[@class=&quot;dataRow even last first highlight&quot;]/th[@class=&quot;dataCell&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
