<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_j_id0j_id110j_id111mainF_1</name>
   <tag></tag>
   <elementGuidId>00a805b3-2321-4c44-bfcf-c91d6b54de3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'j_id0:j_id110:j_id111:mainForm:j_id198' and @name = 'j_id0:j_id110:j_id111:mainForm:j_id198' and @type = 'checkbox']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>html/body/div/div[2]/table/tbody/tr/td[2]/table/tbody/tr/td[1]/span[2]/span[2]/span/span/form/span/div/div/span/span/span/table/tbody/tr[2]/th[2]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_id0:j_id110:j_id111:mainForm:j_id198</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>j_id0:j_id110:j_id111:mainForm:j_id198</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_id0:j_id110:j_id111:mainForm:j_id198&quot;)</value>
   </webElementProperties>
</WebElementEntity>
