<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_j_id0SubmitContactFormj_</name>
   <tag></tag>
   <elementGuidId>6c008531-7ee0-414f-b684-4a69c140f2a0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_id0:SubmitContactForm:j_id47:j_id48:0:assignToPurchaserBtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>j_id0:SubmitContactForm:j_id47:j_id48:0:assignToPurchaserBtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('j_id0:SubmitContactForm',event,{'similarityGroupingId':'j_id0:SubmitContactForm:j_id47:j_id48:0:assignToPurchaserBtn','parameters':{'j_id0:SubmitContactForm:j_id47:j_id48:0:assignToPurchaserBtn':'j_id0:SubmitContactForm:j_id47:j_id48:0:assignToPurchaserBtn','licenseId':'a0a3C000000AUgYQAW'} } );return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Asignar al Comprador</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_id0:SubmitContactForm:j_id47:j_id48:0:assignToPurchaserBtn&quot;)</value>
   </webElementProperties>
</WebElementEntity>
